id = "5e87d2e3-d1cd-4b6c-932a-15b5d1393651"
created_at = "2026-04-01T13:37:46.683109700+00:00"
title = "[context-editor][SVO-RM] Phase 3a: Full PBR Lighting and Depth Buffer Integration"
state = "done"
component = "memory-viewers"
depends_on = ["22801e4f-36bd-43fc-b765-6e456b2bc63a", "8c2f1575-e704-44cb-bfc0-1f908bfc4855"]
phase = "svo-ray-march"
type = "tracker-improvement"
