id = "86de425a-f7cc-4cfb-9a1d-582bc4e352cb"
created_at = "2026-04-01T13:33:39.785350600+00:00"
title = "[context-editor][SVO-RM] Phase 4a: Frustum Culling, Paged SVO Upload and Virtual Address Table"
state = "done"
component = "memory-viewers"
depends_on = ["5eea3447-151b-4f92-9dbf-e89280122d29"]
phase = "svo-ray-march"
type = "tracker-improvement"
