id = "aaaf1d50-e2ee-4352-b9b4-495c7eadb117"
created_at = "2026-07-07T12:06:03.715093300+00:00"
title = "[context-editor][SVO-RM] Phase 1 tracker (de-retro cluster migration)"
state = "planning"
depends_on = ["9ef831d0-0f1d-46db-88bb-e537a37b9606", "febe05b2-ab03-4309-9d84-39aae471e27a"]
effort = "1200"
type = "tracker-improvement"
component = "memory-viewers"
