id = "cf77062c-f663-4ed4-beca-9303795cf973"
created_at = "2026-05-26T16:36:33.745378700+00:00"
title = "[ci] Split viewer workflows to memory-viewers"
state = "done"
type = "tracker-improvement"
component = "memory-viewers"
